### ISSUE TITLE
Segmentation fault when headers are undef.

### ISSUE THREAD

**Issue by bbkr** [net-amqp-rabbitmq/net-amqp-rabbitmq#101]
(note: POD has 'header' instead of 'headers', there is separate issue for it already)

```
$mq->publish(1, 'test', 'Hi there!', {}, {'headers' => undef});
```

Gives segmentation fault.
I know that POD explicitly says what is the expected value, but user should get error message instead of being able to crash whole script.

**Comment by manchicken** [comment]
That's a good point. Thanks for the report.
