### ISSUE TITLE
Bug in reading of ssl_verify_host option?

### ISSUE THREAD

**Issue by fgabolde** [net-amqp-rabbitmq/net-amqp-rabbitmq#111]
The doc says `ssl_verify_host` but it doesn't seem to have an effect. In the XS code I can find a `ssl_verify_hostname` option though.

**Comment by markwellis** [comment]
good catch! I'll try to get this done tonight

**Comment by fgabolde** [comment]
Hello @markwellis, any news on this issue?

**Comment by markwellis** [comment]
@fgabolde sorry, I've been really busy, I've a big list of things. I'll try to get it done tonight
