### ISSUE TITLE
upgrade to rabbitmq-c v0.8.0

### ISSUE THREAD

**Issue by markwellis** [net-amqp-rabbitmq/net-amqp-rabbitmq#112]
add ssl_verify_peer option

**Comment by manchicken** [comment]
@markwellis Did you do this?

**Comment by markwellis** [comment]
I did not. There's some changes in the ssl api in the newer version that should be easy enough to fix. See these TODOs (assuming it's not changed since I wrote them!)

https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/blob/master/RabbitMQ.xs#L1193

**Comment by manchicken** [comment]
I just upgraded to `v0.10.0`, so I think that addresses this. I'm going to mark this in 2.40005.
