### ISSUE TITLE
rabbitmq.thisaintnews.com down?

### ISSUE THREAD

**Issue by fgabolde** [net-amqp-rabbitmq/net-amqp-rabbitmq#126]
The test suite is stuck at the first live test (`t/001_declare_exchange.t`). This is blocking our CI tests; is there another workaround than setting up our own RMQ server and testing against that?

**Comment by markwellis** [comment]
Sorry, the vm hosting the rabbitmq instance was down. It should work now

**Comment by fgabolde** [comment]
Thanks @markwellis for the quick response.
