### ISSUE TITLE
t/ssl/cacert.pem expired

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#128]
```
$  cat t/ssl/cacert.pem | openssl x509 -text | grep -A 2 Validity
        Validity
            Not Before: Oct 11 21:31:55 2015 GMT
            Not After : Oct 10 21:31:55 2016 GMT
```
Consequently t/030_ssl.t fails since this date. See http://matrix.cpantesters.org/?dist=Net-AMQP-RabbitMQ%202.200001;reports=1#sl=7,1

**Comment by markwellis** [comment]
Good catch. I'll fix it now

**Comment by markwellis** [comment]
Should be fixed now. Test is running in jenkins

**Comment by markwellis** [comment]
I need to update the cert in the tests. PR incoming
