### ISSUE TITLE
Travis osx builds failing

### ISSUE THREAD

**Issue by markwellis** [net-amqp-rabbitmq/net-amqp-rabbitmq#139]
see https://travis-ci.org/net-amqp-rabbitmq/net-amqp-rabbitmq/builds/169477363

they're much too fast, looking at one ( https://travis-ci.org/net-amqp-rabbitmq/net-amqp-rabbitmq/jobs/169477365 ) I see it failed (with exit code 0!)

```
Can't load module Devel::Cover at /usr/bin/prove5.18 line 12.

/Users/travis/build/net-amqp-rabbitmq/net-amqp-rabbitmq/travis/script: line 24: cover: command not found

The command "$TRAVIS_BUILD_DIR/travis/script" exited with 0.
```

so two fixes, make it not exit 0 on failure, and install devel::cover

**Comment by markwellis** [comment]
http://stackoverflow.com/questions/821396/aborting-a-shell-script-if-any-command-returns-a-non-zero-value

**Comment by grim8634** [comment]
Yeah, I can grab this one too.

**Comment by grim8634** [comment]
Travis have dropped Perl support for OSx :(. I'm trying to sort a workaround for this. Adding set -e worked, for catching the failures. I'll update once I know more.

https://docs.travis-ci.com/user/languages/perl/

**Comment by manchicken** [comment]
I totally see that it says that... but the builds do seem to be working now: https://travis-ci.org/net-amqp-rabbitmq/net-amqp-rabbitmq/jobs/184007578

**Comment by markwellis** [comment]
It's good that they're no longer failing. However, all the osx tests are on system perl-5.18

**Comment by manchicken** [comment]
This seems to have been fixed.
