### ISSUE TITLE
Feature request: way to disable rabbitmq extensions to AMQP

### ISSUE THREAD

**Issue by skibrianski** [net-amqp-rabbitmq/net-amqp-rabbitmq#143]
Hello.

We need to publish to queues that will be read by python's celery and pika drivers, and unfortunately those drivers do not appear to support rabbitMQ extensions - they blow up when they read (most) messages delivered by Net::AMQP::RabbitMQ 0.005007 through 2.3 (did not test 0.005005 and under) because they are sent across the wire with field type 'x' (byte array) instead of 'S' ( long string ) - as described here: https://www.rabbitmq.com/amqp-0-9-1-errata.html.

While the ability to distinguish raw bytes from utf8 perl strings is desirable, it would be preferble to have a way to disable RabbitMQ extensions, ideally via a flag set at constructor time.

Thanks!
Brian Szymanski, ThinkGeek

**Comment by skibrianski** [comment]
You may close this bug report, I see now that there is an option added in Net::AMQP::RabbitMQ that supports this.

**Comment by markwellis** [comment]
That was easy :)
