### ISSUE TITLE
ssl doc patch

### ISSUE THREAD

**Issue by abraxxa** [net-amqp-rabbitmq/net-amqp-rabbitmq#147]
> For now there is no option to disable ssl peer checking, meaning to use ssl, ssl_cacert is required.

isn't correct any more as there is the `ssl_verify_host` option.

**Comment by markwellis** [comment]
We can upgrade the library now and add that check

**Comment by manchicken** [comment]
@markwellis Did we ever do this?

**Comment by manchicken** [comment]
At this time, there is no option to disable peer checking. I'm marking this as an enhancement for the future.

**Comment by manchicken** [comment]
Sorry, misread. This issue has already been resolved for a while.
