### ISSUE TITLE
REQUEST: optionally leave connection alive in net_amqp_rabbitmq_DESTROY to allow forking

### ISSUE THREAD

**Issue by Deracination** [net-amqp-rabbitmq/net-amqp-rabbitmq#151]
To use Net::AMQP::RabbitMQ with a listener which forks worker processes it is necessary to close the connection in the child but keep it alive in the parent.

The current implementation of net_amqp_rabbitmq_DESTROY always closes and destroys the connection.

I have worked around this by removing _DESTROY in RabbitMQ.xs and replacing it with _demolish called instead of relying on auto-close when the queue variable goes out of scope.

A better method might be the 'persistent connection' pconnect which is provided in the PHP https://pecl.php.net/package/amqp lib. Sorry but I don't know enough about XS to implement this!

**Comment by mjegh** [comment]
I hit this problem today. I was using Log::Log4perl and Log::Log4perl::Appender::RabbitMQ and had code using Parallel::ForkManager. When the forked children died it ended up in Net::AMQP::RabbitMQ::Destroy and killed my connection.
I did have a go at looking at implementing something like DBI's AutoInactiveDestroy (http://search.cpan.org/~timb/DBI-1.640/DBI.pm#AutoInactiveDestroy) but N::A::R as far as I could see the new method doesn't do anything and everything hangs off the structure created in connect. Basically, when AutoInactiveDesctroy is set the constructor stores the PID and in the DESTROY it refuses to destroy if the PID differs from the one in the constructor.

**Comment by markwellis** [comment]
This should be fixed now
