### ISSUE TITLE
Cleanup rabbitmq test server

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#154]
Every test run seems to leave two exchanges and two queues on rabbitmq.thisaintnews.com. This does not sound much, but over time there were about 6000 exchanges and queues cumulated on the server. Also, the test suite started to fail (or to hang) recently. I don't know if this was due to the many queues/exchanges on the server, but I made a cleanup and now things seem to work again (i.e. the tests pass again).

It would be good if the test resources would be automatically deleted:
* nar_queue-*-t_002_publish_consume.t
* nar_queue-*-t_032_cancel_consume_ack_exception.t
* nar_excahnge-*-t_002_publish_consume.t
* nar_excahnge-*-t_032_cancel_consume_ack_exception.t

And maybe there should be an additional cronjob which looks for other leftover (e.g. due to test script crashes) and removes it.

**Comment by manchicken** [comment]
I totally thought we were cleaning up after ourselves on the tests. We absolutely should add cleanup blocks to these tests.

**Comment by markwellis** [comment]
Hmm yeah they should be cleaned up. They must have been missed.

There used to a be cron on the server that reset rabbitmq weekly, but
then it was quickly used for something else and I disabled it :/

On Mon, 11 Jun 2018, at 5:51 AM, Michael D. Stemle, Jr. wrote:
> I totally thought we were cleaning up after ourselves on the tests. We
> absolutely should add cleanup blocks to these tests.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:

  1. https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/issues/154#issuecomment-396121596

**Comment by bombsimon** [comment]
The Travis script in the [rabbitmq-c-bump](https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/blob/rabbitmq-c-bump/travis/before_script) buids and runts RabbitMQ locally with SSL-support. Due to this `NAR::Helper` will connect to localhost with SSL instead of rabbitmq.thisaintnews.com.

I don't know if this is something that will be kept when/if the branch will be merged.

**Comment by eserte** [comment]
Currently rabbitmq.thisaintnews.com is not reachable, maybe there was again an exchange+queue fillup?

**Comment by markwellis** [comment]
Sorry my bad. Sometimes the container doesn't start on reboot

**Comment by eserte** [comment]
The rabbitmq test server seems to work, and the tests are passing again. Still the original issue (missing cleanup) looks like it is unresolved --- there are currently more than 100 test exchanges and queues on the server.

**Comment by markwellis** [comment]
I've changed the test server to one hosted by cloudamqp, and added better cleanup code
