### ISSUE TITLE
Tests failing (dev rabbitmq not available)

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#157]
Since some days the test suite fails --- it seems that rabbitmq.thisaintnews.com does not work anymore.

First such failure at CPAN Testers: http://www.cpantesters.org/cpan/report/5f93fb0c-9a7b-11e8-ad0d-b24a1fb6a4dc

**Comment by markwellis** [comment]
Sorry that's my bad. I've fixed it

**Comment by eserte** [comment]
Thanks!
