### ISSUE TITLE
Connect call does not take advantage of handshake_timeout

### ISSUE THREAD

**Issue by SineSwiper** [net-amqp-rabbitmq/net-amqp-rabbitmq#158]
The `net_amqp_rabbitmq_connect` call in the XS code passes the timeout to `amqp_socket_open_noblock`.  However, this only impacts the initial connection, and not the login time.  RabbitMQ has a `conn->handshake_timeout`, but it must be set after the `conn` is created.  The default of 5 seconds is used otherwise.

**Comment by minusdavid** [comment]
My connection isn't timing out at all. I wonder if this is related...

**Comment by manchicken** [comment]
I'm unable to replicate this. If you're able to consistently replicate this, please re-open or submit a new issue with a test so that I can dig deeper.
