### ISSUE TITLE
Can't connect to hornet.rmq.cloudamqp.com:15672

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#173]
t/024_boolean_header_fields.t fails on almost all of my smokers (except on systems without LWP::UserAgent installed, where this test is skipped):
```
#   Failed test 'Publishing message with boolean value true'
#   at t/024_boolean_header_fields.t line 38.
Publishing booltest message failed: 500 Can't connect to hornet.rmq.cloudamqp.com:15672
Content-Type: text/plain
Client-Date: Mon, 10 Jun 2019 13:37:24 GMT
Client-Warning: Internal response

Can't connect to hornet.rmq.cloudamqp.com:15672

Operation timed out at /usr/perl5.22.2t/lib/site_perl/5.22.2/LWP/Protocol/http.pm line 47.
# Looks like your test exited with 60 just after 7.
t/024_boolean_header_fields.t .......... 
Dubious, test returned 60 (wstat 15360, 0x3c00)
Failed 6/12 subtests 
```

**Comment by manchicken** [comment]
The host seems down. 

~ Michael D. Stemle, Jr.

**Comment by markwellis** [comment]
This test won't work now as cloudamqp don't allow access to the management interface the same way the old server did

**Comment by manchicken** [comment]
We may be able to redo this test using the Java AMQP client. If we did it that way, how would we want to manage that dependency?

We could try using the C library, but that seems rather circular for this test. 

~ Michael D. Stemle, Jr.
