### ISSUE TITLE
cannot compile with ssl support with macports

### ISSUE THREAD

**Issue by kiwiroy** [net-amqp-rabbitmq/net-amqp-rabbitmq#178]
The `Makefile.PL` expects homebrew when finding openssl.

https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/blob/a968abb890f65181a5500ef31883ecd4a77c187c/Makefile.PL#L33-L44

**Comment by manchicken** [comment]
Closing (should have closed this a while ago).
