### ISSUE TITLE
Getting messages from queue I stopped consuming

### ISSUE THREAD

**Issue by murdegern** [net-amqp-rabbitmq/net-amqp-rabbitmq#181]
Hi,

I'm using Net::AMQP::RabbitMQ 2.30000 and hitting a strange problem (or perhaps I'm just doing something stupid):

Directly after connecting, my client script opens a channel (2), pulls one message from a special queue with system info, rejects it with requeue so the next client will find it, too, and closes the channel again.

Then it opens another channel (1), and listens to another queue, where the real messages come in. Now, SOMETIMES, the same message I rejected on the sysinfo pops up again in recv. And my script is deeply disturbed :-D

The code amounts to this (I took out the part where the sysinfo is not there and must be generated by the client):

```perl
# pull sysinfo
{
  $mq->channel_open(2);
  $mq->exchange_declare(2, 'sysinfo', {});
  $mq->queue_declare(2, 'sysinfo', {auto_delete=>0});
  $mq->queue_bind(2, 'sysinfo', 'sysinfo', 'sysinfo');
  my $tag = $mq->consume(2, 'sysinfo', { no_ack => 0 });
  my $msg = $mq->recv(3000);
  $mq->cancel(2, $tag);
  $mq->reject(2, $msg->{delivery_tag}, 1) if $msg;
  $mq->channel_close(2);
}

# listen on work queue
$mq->channel_open(1);
$mq->exchange_declare(1, 'otherxchg', {});
$mq->queue_declare(1, 'otherqueue', {durable => 1, auto_delete => 0});
$mq->queue_bind(1, 'otherqueue', 'otherxchg', 'otherqueue');
my $tag = $mq->consume(1, 'otherqueue', { no_ack => 0 });
my $msg = $mq->recv(60000);
# now, sometimes, $msg holds the same message I got in the first recv().
```
Is there some way to avoid this?

Thanks and regards,
Torsten

**Comment by manchicken** [comment]
@murdegern I'm a little fuzzy about what you're seeing here. Is there any way that you could write a quick test script to demonstrate the problem?

**Comment by manchicken** [comment]
No response from submitter.
