### ISSUE TITLE
Do not inflate to a Math::Int64 object unless you crossed 54 bits

### ISSUE THREAD

**Issue by mrmuskrat** [net-amqp-rabbitmq/net-amqp-rabbitmq#182]
The integer 28200 shouldn't need to be inflated into a Math::Int64 object but that's exactly what happens. The inflation should only be needed if you cross the 54 bit threshold.

**Comment by manchicken** [comment]
Can you please be a bit more specific about the case you've got? If you have a use case where this is a problem, that'd also be helpful. Test code is very much appreciated.

**Comment by manchicken** [comment]
I think a good next step on this issue would be to add some tests for integers which need varying sizes, and then only use the larger object when it's needed.
