### ISSUE TITLE
Most fail reports fail due t/012_timeout.t 

### ISSUE THREAD

**Issue by andk** [net-amqp-rabbitmq/net-amqp-rabbitmq#183]
As per subject. At the moment I count exactly 52 of 62. Sample fail report: http://www.cpantesters.org/cpan/report/105339117

Diagnostics:

```
#   Failed test 'timeout'
#   at t/012_timeout.t line 26.
#     '2.956607'
#         <
#     '0.5'
# Looks like you failed 1 test of 2.
t/012_timeout.t ........................ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
```

**Comment by manchicken** [comment]
@andk I think that this may have been due to a problem with the test server that the tests use. Is this still an issue?
