### ISSUE TITLE
Property delivery_mode not working for publishing messages

### ISSUE THREAD

**Issue by dschiffel** [net-amqp-rabbitmq/net-amqp-rabbitmq#184]
Hi. 
Property delivery_mode not working for publishing messages. My code example: 
```
sub sendResponse {
    my %args = @_;
    $responseChannel->publish(
        channel =>'',
        routing_key => $responseQueue,
        body => encode_json(\%args),
        options => { exchange => 'messages' },
        props => { delivery_mode => 2 }
    );
}
```
Here is your documentation: 
https://metacpan.org/pod/Net::AMQP::RabbitMQ#publish($channel,-$routing_key,-$body,-$options,-$props)

But there is never used argument $props in your package AnyEvent::RabbitMQ::Channel  for _publish subroutine or _header subroutine. 

Can you write me how I can set delivery_mode => 2 for published messages? 
Thanks.
DS.

**Comment by manchicken** [comment]
This is a pretty well-used feature, I'm having a hard time believing that it's not working properly. Why do you think it's not working? Are you seeing the management screens showing the delivery_mode being wrong?

**Comment by dschiffel** [comment]
@manchicken Right. I still seeing in the RBMQ management console for every message "delivery_mode=1".

**Comment by manchicken** [comment]
Can you send a screen cap on this? Also, can you give us a more in-context code sample? I want to make sure I'm not missing anything. I just followed the code through to the C code and it looks fine. Our automated tests also verify this parameter (though we should probably do more testing here).

If you could, would it be possible for you to demonstrate this by adding a failing test case to this test here? https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/blob/68d907ea72632c8e2df51f16852b1e521b283131/t/002_publish_consume.t

**Comment by manchicken** [comment]
@dschiffel Are you still having this problem? I cannot replicate this issue.

**Comment by manchicken** [comment]
@dschiffel Hey, I cannot replicate this issue. If you're still seeing this, please let me know how to dig in more and I'm happy to re-open this issue.
