### ISSUE TITLE
Documentation unclear about librabbitmq dependency

### ISSUE THREAD

**Issue by minusdavid** [net-amqp-rabbitmq/net-amqp-rabbitmq#205]
https://metacpan.org/pod/release/MSTEMLE/Net-AMQP-RabbitMQ-2.40008/RabbitMQ.pm describes itself as a wrapper around librabbitmq. However, I expected this to mean that I needed to have installed the librabbitmq package on my OS (like how you typically need libpq installed separately from an upstream repo when using a Perl library that is a wrapper around libpq). 

However, when I noticed Net::AMQP::RabbitMQ working without that dependency, I was scratching my head. 

I'm not super familiar with XS and using C with Perl, but at a glance the git looks like you're embedding librabbitmq within this project and presenting it as a shared object for Net::AMQP::RabbitMQ?

That's awesome as it really makes things easier for me, but perhaps the documentation should be updated to reflect that the librabbitmq dependency is bundled with the Net::AMQP::RabbitMQ library?

**Comment by abraxxa** [comment]
But it should be noted in the docs, that compiler support is required as well as some header files from devel packages like openssl/bio.h.

**Comment by manchicken** [comment]
As this is a module with C bindings, compiler support will always be required. That's a pretty common requirement for Perl modules. OpenSSL@1.1.x is documented in the README.md.
