### ISSUE TITLE
Add timeout for amqp_login

### ISSUE THREAD

**Issue by minusdavid** [net-amqp-rabbitmq/net-amqp-rabbitmq#206]
The connection timeout appears to only be for the TCP socket connection. 

Looking at https://metacpan.org/source/MSTEMLE/Net-AMQP-RabbitMQ-2.40008/RabbitMQ.xs, if you successfully create a TCP connection, but there is lag in the login, you're at the mercy of a hard-coded 12 second timeout at https://metacpan.org/source/MSTEMLE/Net-AMQP-RabbitMQ-2.40008/amqp_connection.c#L62

I proved that one by using netcat to provide the TCP socket but not respond to the protocol.

In real world terms, I suppose this could happen if you were using a load balancer in front of a RabbitMQ cluster (rather than using round robin DNS or a configurable list of nodes).

**Comment by minusdavid** [comment]
Note that there should be support for this as per https://github.com/alanxz/rabbitmq-c/issues/403

**Comment by minusdavid** [comment]
Oh this one is quite interesting too... https://github.com/alanxz/rabbitmq-c/pull/404

That actually sounds ideal, as it would cover things like queue declare, publish, etc.

**Comment by manchicken** [comment]
I'll see what I can do on this one.

**Comment by manchicken** [comment]
@minusdavid that seemed pretty easy. I'm blocked on Travis-CI (their new payment model requires approval for open source project builds if you don't want to pay for them), but I expect that to be resolved within the week.

If this works, I'll have it in the release at the end of October.
