### ISSUE TITLE
no_ack  during consume

### ISSUE THREAD

**Issue by pgonis** [net-amqp-rabbitmq/net-amqp-rabbitmq#207]
The option no_ack => 0  during consume of this class  is not leading to Dead Letter Exchanges. From the other hand when the TTL is setup is working properly.

**Comment by petdance** [comment]
FYI: I have been fighting for the past 2 days on no_ack and consume, and it seems to be that I have had to have `durable` turned on and `auto_delete` turned off for the queue.
