### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by PPetky** [net-amqp-rabbitmq/net-amqp-rabbitmq#210]
Hi!

I'm trying to move with Net::AMQP::RabbitMQ perl component with SSL encrypting, TLS v1,2 but I have this respond
```
opening socket: SSL handshake failed
```
The strangest thing is that there is no log records. So, the big question is there a solution or workaround? 
I use these parameters (maybe I'm doing something wrong)
```
my %par = (
    user => 'user',
    password => 'password',
    port => 5671,
    ssl => 1,
    ssl_verify_host => 0,
    ssl_cacert => '/etc/rabbitmq/ssl/ca',
    ssl_cert => '/etc/rabbitmq/ssl/crt',
    ssl_key => '/etc/rabbitmq/ssl/key'
);
```
Thanks

**Comment by manchicken** [comment]
Yeah, that's weird. You may need to turn SSL debugging up a little. If you can come up with a test which verifies this against the test server with throw-away certs, I can't really troubleshoot this much for you.

**Comment by manchicken** [comment]
I'm gonna close this for now, but if you can find a way to consistently replicate this (without disclosing crypto keys), please let me know and we can totally re-open this.
