### ISSUE TITLE
If channel_open is called twice and then you try to publish, the module seems to cause a blocking wait of some type.

### ISSUE THREAD

**Issue by manchicken** [net-amqp-rabbitmq/net-amqp-rabbitmq#22]
If channel_open is called twice and then you try to publish, the module seems to cause a blocking wait of some type.

**Comment by markwellis** [comment]
I don't think this is an issue now, I just tried it and it errored out with 
` Opening channel: server connection error 504, message: CHANNEL_ERROR - second 'channel.open' seen` 

which is what I thought the error was (not checking rpc error status)

We must have fixed it some time in the last 2 years. Closing.

```perl
use strict;
use warnings;
  
use Net::AMQP::RabbitMQ;       
  
my $mq = Net::AMQP::RabbitMQ->new();
$mq->connect('localhost',
             { port => 5672,
               user => 'guest',
               password => 'guest' });         
  
my $channel = 1; 
$mq->channel_open($channel);

#dies here
$mq->channel_open($channel);
  
$mq->publish( $channel, "something", "hello");
```
