### ISSUE TITLE
SSL fails on Debian again

### ISSUE THREAD

**Issue by mhterres** [net-amqp-rabbitmq/net-amqp-rabbitmq#224]
Hey guys.

I'm really sorry to inform you, but looks like issue #186  is back.

t/030_ssl.t ............................ 1/9 
#   Failed test 'connected'
#   at t/030_ssl.t line 30.

#   Failed test 'channel_open'
#   at t/030_ssl.t line 31.

#   Failed test 'exchange declare'
#   at t/030_ssl.t line 33.

#   Failed test 'queue declare'
#   at t/030_ssl.t line 34.

#   Failed test 'queue bind'
#   at t/030_ssl.t line 35.

#   Failed test 'drain queue'
#   at t/030_ssl.t line 36.

#   Failed test 'consume'
#   at t/030_ssl.t line 38.

#   Failed test 'publish'
#   at t/030_ssl.t line 39.

#   Failed test 'payload matches'
#   at t/030_ssl.t line 53.
#     Structures begin differing at:
#          $got = undef
#     $expected = HASH(0x55eb25642f88)
# Looks like you failed 9 tests of 9.
t/030_ssl.t ............................ Dubious, test returned 9 (wstat 2304, 0x900)
Failed 9/9 subtests 
t/031_magic_header_fields.t ............ ok     
t/032_cancel_consume_ack_exception.t ... ok     
t/033_fork.t ........................... ok   

Test Summary Report
-------------------
t/030_ssl.t                          (Wstat: 2304 Tests: 9 Failed: 9)

I tested with Debian 10 and 11 and had the same issue.

Any ideas?

Thank you.

**Comment by manchicken** [comment]
Please try again with 2.40010, just released.
