### ISSUE TITLE
Timeout in "connect" method doesn't appear to work in 2.40008

### ISSUE THREAD

**Issue by minusdavid** [net-amqp-rabbitmq/net-amqp-rabbitmq#226]
I'm having an issue where the AMQP socket connection seems to drop out. I try to connect after and I get an error "Logging in: invalid AMQP data". I try to connect again after that and it just hangs indefinitely...

**Comment by minusdavid** [comment]
Working around it by discarding the whole object after I get an error of "ack failed because AMQP socket connection was closed", and then just starting over from fresh...

RabbitMQ seems to be dropping my connection after about 30 seconds with this error:
2022-04-06 16:55:58.570 [error] <0.5946.15> closing AMQP connection <0.5946.15> ([::1]:34250 -> [::1]:5672):
{writer,send_failed,{error,timeout}}

**Comment by minusdavid** [comment]
Looks like RabbitMQ dropping off might relate to the basic_qos and prefetch but having issues getting the library to set that too..

**Comment by minusdavid** [comment]
perl: amqp_socket.c:123: amqp_socket_send: Assertion `self' failed.

**Comment by minusdavid** [comment]
I imagine the connect issue might be something out... maybe not cleaning up the object after the disconnection...

In any case, got basic_qos() to work in the end, and RabbitMQ no longer dropping off, so not so worried about the connection timeout anymore...

**Comment by minusdavid** [comment]
Might be a good idea to add a basic_qos() example in the pod though. It makes a world of difference it seems.

**Comment by manchicken** [comment]
Are you still seeing this in 2.40010?

**Comment by manchicken** [comment]
> Might be a good idea to add a basic_qos() example in the pod though. It makes a world of difference it seems.

I added that example to #233.

@minusdavid, are you still seeing this issue in the #233 PR?
