### ISSUE TITLE
Compilation fails on FreeBSD with -Duselongdouble (related to Perl_pow)

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#227]
On FreeBSD systems where perl is compiled with -Duselongdouble the compilation of RabbitMQ.xs fails:
```
cc -c  -I. -Irabbitmq-include -Irabbitmq-include/unix  -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -O2 -pipe    -DVERSION=\"2.40009\"  -DXS_VERSION=\"2.40009\" -DPIC -fPIC "-I/usr/perl5.35.11Dp/lib/5.35.11/amd64-freebsd-ld/CORE"  -DHAVE_SOCKET -DHAVE_POLL -DAMQ_PLATFORM='"Perl_freebsd_v5.35.11"' -DNAR_HAVE_OPENSSL RabbitMQ.c
...
RabbitMQ.xs:76:31: error: initializer element is not a compile-time constant
        const NV DOUBLE_POW = Perl_pow(10., DBL_DIG );
                              ^~~~~~~~~~~~~~~~~~~~~~~
/usr/perl5.35.11Dp/lib/5.35.11/amd64-freebsd-ld/CORE/perl.h:2255:25: note: expanded from macro 'Perl_pow'
#       define Perl_pow powl
                        ^
...
```

**Comment by manchicken** [comment]
Do you have a Dockerfile you could lend me that would help me test with whatever your config is?

**Comment by eserte** [comment]
IMHO docker does not work with FreeBSD (unless you have a FreeBSD host system).

**Comment by manchicken** [comment]
That tells you how often I use FreeBSD. Is there any other way that you could automate a build that I could test in? 

EC2 snapshot AMI? Just trying to see how I can get in and troubleshoot.

**Comment by manchicken** [comment]
I'm gonna try to see if I can replicate this on 5.36.x with `perlbrew` using `--ld` on GNU/Linux.

**Comment by manchicken** [comment]
No luck, this isn't happening on GNU/Linux even with `uselongdouble`
