### ISSUE TITLE
Compiling on an up to date Mac fails

### ISSUE THREAD

**Issue by davehodg** [net-amqp-rabbitmq/net-amqp-rabbitmq#228]
Probably not really your fault:

```
In file included from amqp_openssl_bio.c:24:
rabbitmq-include/amqp_openssl_bio.h:26:10: fatal error: 'openssl/bio.h' file not found
#include <openssl/bio.h>
```
I have bio.h at `/usr/local/Cellar/openssl@3/3.0.2/include/openssl/bio.h`

It seem like lots of other things ship with bio.h!

**Comment by manchicken** [comment]
Right now we're stuck with openssl@1.1 using pkg-config. I'm going to try to upgrade to openssl@3, but that's not done yet.
