### ISSUE TITLE
Building on openSUSE fails with 2.40010

### ISSUE THREAD

**Issue by perlpunk** [net-amqp-rabbitmq/net-amqp-rabbitmq#232]
https://build.opensuse.org/package/live_build_log/devel:languages:perl:autoupdate/perl-Net-AMQP-RabbitMQ/standard/x86_64
I'll just paste the last lines here:
```
[   23s] + /usr/bin/mkdir -p /home/abuild/rpmbuild/BUILDROOT/perl-Net-AMQP-RabbitMQ-2.40010-11.1.x86_64/usr/share/doc/packages/perl-Net-AMQP-RabbitMQ
[   23s] + cp -pr Changes /home/abuild/rpmbuild/BUILDROOT/perl-Net-AMQP-RabbitMQ-2.40010-11.1.x86_64/usr/share/doc/packages/perl-Net-AMQP-RabbitMQ
[   23s] + cp -pr CODE_OF_CONDUCT.md /home/abuild/rpmbuild/BUILDROOT/perl-Net-AMQP-RabbitMQ-2.40010-11.1.x86_64/usr/share/doc/packages/perl-Net-AMQP-RabbitMQ
[   23s] + cp -pr CONTRIBUTING.md /home/abuild/rpmbuild/BUILDROOT/perl-Net-AMQP-RabbitMQ-2.40010-11.1.x86_64/usr/share/doc/packages/perl-Net-AMQP-RabbitMQ
[   23s] + cp -pr MANIFEST /home/abuild/rpmbuild/BUILDROOT/perl-Net-AMQP-RabbitMQ-2.40010-11.1.x86_64/usr/share/doc/packages/perl-Net-AMQP-RabbitMQ
[   23s] + cp -pr 3 /home/abuild/rpmbuild/BUILDROOT/perl-Net-AMQP-RabbitMQ-2.40010-11.1.x86_64/usr/share/doc/packages/perl-Net-AMQP-RabbitMQ
[   23s] cp: cannot stat '3': No such file or directory
[   23s] + :
[   23s] + cp -pr README.md /home/abuild/rpmbuild/BUILDROOT/perl-Net-AMQP-RabbitMQ-2.40010-11.1.x86_64/usr/share/doc/packages/perl-Net-AMQP-RabbitMQ
[   23s] + RPM_EC=0
[   23s] ++ jobs -p
[   23s] + exit 0
[   23s] error: File not found: /home/abuild/rpmbuild/BUILDROOT/perl-Net-AMQP-RabbitMQ-2.40010-11.1.x86_64/usr/share/doc/packages/perl-Net-AMQP-RabbitMQ/3
```

perl: 5.34.1

Let me know if you need more info.

**Comment by manchicken** [comment]
Blah; it looks like that one has the bad manifest that I could have sworn I pulled before publishing... but clearly did not. I've got this fixed in 2.40011.

**Comment by manchicken** [comment]
Can you try the PR in #233 out to see if that resolves this issue for you?

**Comment by perlpunk** [comment]
I think I might need the tarball to test this. We're not installing from the git sources...

**Comment by manchicken** [comment]
Ok, so you need a dist tarball, not just one with the git source, yeah?

~ Michael D. Stemle, Jr.

**Comment by manchicken** [comment]
Can you try this tarball?
[Net-AMQP-RabbitMQ-2.40010.tar.gz](https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/files/9002440/Net-AMQP-RabbitMQ-2.40010.tar.gz)

**Comment by perlpunk** [comment]
Sorry for the delay.
Unfortunately I get the same error message:
https://build.opensuse.org/package/live_build_log/home:tinita:branches:devel:languages:perl:autoupdate/perl-Net-AMQP-RabbitMQ/standard/x86_64

**Comment by manchicken** [comment]
It looks like your `.spec` file has the old file "`MANIFEST 3`" in it still. Line 65: https://build.opensuse.org/package/view_file/home:tinita:branches:devel:languages:perl:autoupdate/perl-Net-AMQP-RabbitMQ/perl-Net-AMQP-RabbitMQ.spec?expand=1

Could you try correcting that and try again with the same tarball?

**Comment by perlpunk** [comment]
oooh, sorry! I got it now.
Yes, I regenerated the spec and now the build passes \o/

**Comment by manchicken** [comment]
w00h00!
