### ISSUE TITLE
Install / Tests Failing - appears to be due to invalid test credentials

### ISSUE THREAD

**Issue by drees** [net-amqp-rabbitmq/net-amqp-rabbitmq#240]
Tests started failing on Ubuntu Focal 20.04 (building in Docker) - not quite sure what the cause is (same thing worked in April).

Here's a snippet from the cpanm build log:

```
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/000_use_ok.t ......................... ok

#   Failed test 'connected'
#   at t/001_declare_exchange.t line 11.

#   Failed test 'channel_open'
#   at t/001_declare_exchange.t line 12.

#   Failed test 'default exchange declare'
#   at t/001_declare_exchange.t line 14.

#   Failed test 'internal exchange declare'
#   at t/001_declare_exchange.t line 16.

#   Failed test 'direct declare auto_delete'
#   at t/001_declare_exchange.t line 25.

#   Failed test 'internal exchange declare auto_delete'
#   at t/001_declare_exchange.t line 34.
# Looks like you failed 6 tests of 6.
t/001_declare_exchange.t ............... 
Dubious, test returned 6 (wstat 1536, 0x600)
Failed 6/6 subtests 
```

Here's a simple Dockerfile that reproduces the issue:

```
FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y --no-install-recommends install \
    cpanminus gcc libc6-dev libssl-dev make \
    && cpanm Net::AMQP::RabbitMQ

CMD [ "/bin/bash" ]
```

**Comment by Vaelatern** [comment]
Could the username/password baked into the tests no longer be accurate?

**Comment by drees** [comment]
I had a chance to dig into this in detail and yes, it appears that there is an issue with the credentials used for the test cases.
I updated the following settings and pointed them to a test instance of RabbitMQ and then the test cases pass OK (don't have SSL set up on my test instance). Tweak settings to suit your environment and actual username/password to suit.

```MQADMINPORT=15672
MQADMINPROTOCOL=http
MQHOST=localhost
MQPASSWORD=password
MQSKIPSSL=1
MQUSERNAME=username
MQVHOST=/test```

**Comment by manchicken** [comment]
Yeah, the folks at `cloudamqp.com` have notified us that they're not going to permit us to use them for testing anymore since that does require us publishing the credentials for that instance. I'm looking into alternative options, but my top priority right now is figuring out what to do about the terminal code rot in this module.
