### ISSUE TITLE
Support required for upgrading to latest Net::AMQP::RabbitMQ

### ISSUE THREAD

**Issue by kaniMano** [net-amqp-rabbitmq/net-amqp-rabbitmq#244]
We are using older version of Net::AMQP::RabbitMQ which is 0.004004. 
Rabbitmq version is 3.8.9
<img width="365" alt="image" src="https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/assets/28338717/81bae258-8de8-4830-909b-60489fbe9c71">

Erlang version is 23.1-2,
<img width="544" alt="image" src="https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/assets/28338717/6539fbcf-ec10-45bd-a8f4-542d8a0ec6a1">

Now we are planning to upgrade to latest Net::AMQP::RabbitMQ version which is 2.40010.

We would like to know if we can upgrade to 2.40010 with the existing rabbitmq and erlang versions.

**Comment by manchicken** [comment]
This module isn't tied to any particular RabbitMQ or Erlang versions. This module is using C bindings to communicate with AMQP protocol version 0.9.1.
