### ISSUE TITLE
Test case failures seen while installing Net::AMQP::RabbitMQ

### ISSUE THREAD

**Issue by kaniMano** [net-amqp-rabbitmq/net-amqp-rabbitmq#245]
OS : RHEL8

We are trying to install latest version of Net::AMQP::RabbitMQ, but while installing using below command,
**cpan Net::AMQP::RabbitMQ**

But we are seeing lot of test case failures and its getting installed only when we force it.
**cpan -f Net::AMQP::RabbitMQ**

[cpan_failures.txt](https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/files/14602413/cpan_failures.txt)

These failures are expected one ? or we can proceed with force installation. Is there a way to skip the test case execution ?
Please share your inputs.

**Comment by manchicken** [comment]
Unfortunately, this module no longer has public infrastructure it can use, though all of the old tests assumed we would have that public infrastructure forever. In #250 all tests which depend on active RabbitMQ environments at test-time will skip if environment variables which control the tests are not defined. For more information on those environment variables, [please see documentation on running the test suite here](https://metacpan.org/pod/Net::AMQP::RabbitMQ#RUNNING-THE-TEST-SUITE).

These changes will be released with version 2.40012 coming soon.
