### ISSUE TITLE
Build fails on Amazon Linux 2 

### ISSUE THREAD

**Issue by rlauer6** [net-amqp-rabbitmq/net-amqp-rabbitmq#251]
Trying to build version 2.40012 fails (version 2.40010 succeeds)

```
In file included from amqp_openssl.c:31:0:

/usr/include/openssl/ssl.h:2087:10: note: expected 'const SSL_METHOD * {aka const struct ssl_method_st *}' but argument is of type 'int'

 SSL_CTX *SSL_CTX_new(const SSL_METHOD *meth);

          ^~~~~~~~~~~

amqp_openssl.c: In function 'get_tls_version':

amqp_openssl.c:543:22: error: 'TLS1_3_VERSION' undeclared (first use in this function); did you mean 'TLS1_2_VERSION'?

       *tls_version = TLS1_3_VERSION;

                      ^~~~~~~~~~~~~~

                      TLS1_2_VERSION


```

**Comment by manchicken** [comment]
That's odd. Can you give me more details about the system? Info like the openssl version, as well as possibly the build log would be helpful.

**Comment by manchicken** [comment]
Yeah, the earliest version supported is 1.1.1, but even that version of OpenSSL is no longer supported.

I'm sorry, but I can't support versions which are end-of-life.

https://endoflife.date/openssl

**Comment by manchicken** [comment]
Also, Amazon Linux 2 is end-of-life in less than a year. 

https://endoflife.date/amazon-linux

**Comment by rlauer6** [comment]
Understood. Companies unfortunately do not upgrade so perhaps adding a comment in the docs would help those of us working in legacy stacks that will never be upgraded.

**Comment by manchicken** [comment]
Yeah, it mentions on the bottom of the `README.md` mentions that the module supports v3.
