### ISSUE TITLE
Improve the test suite

### ISSUE THREAD

**Issue by autarch** [net-amqp-rabbitmq/net-amqp-rabbitmq#27]
This test seems to rely on some state left over from previous tests.

I didn't try all the tests, but some seem to pass if run in isolation, so it's not a problem everywhere.

**Comment by manchicken** [comment]
Yeah, I think that test uses a queue or exchange which was declared in a
prior test. I've been meaning to harden that one but I have been working on
other issues... namely the one where sometimes RPC calls lead to the server
sending responses back and those getting confused on the wire for responses
expected from later calls.

On Mon, Jan 12, 2015 at 2:29 PM, Dave Rolsky <notifications@github.com>
wrote:

> This test seems to rely on some state left over from previous tests.
>
> I didn't try all the tests, but some seem to pass if run in isolation, so
> it's not a problem everywhere.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markwellis/net-amqp-rabbitmq/issues/27>.
>



-- 
~ Michael D. Stemle, Jr.

**Comment by autarch** [comment]
Moving setup/teardown to a library might be good. This is also an argument for going whole hog with Test::Class or Test::Class::Moose.

**Comment by manchicken** [comment]
Agree completely.

On Mon, Jan 12, 2015 at 4:35 PM, Dave Rolsky <notifications@github.com>
wrote:

> Moving setup/teardown to a library might be good. This is also an argument
> for going whole hog with Test::Class or Test::Class::Moose.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markwellis/net-amqp-rabbitmq/issues/27#issuecomment-69650608>
> .
>



-- 
~ Michael D. Stemle, Jr.

**Comment by autarch** [comment]
This is pretty straightforward. All the tests uses the same exchange, queue, & routing. The `002_publish.t` test ends by publishing (but not getting) a message which `003_consume.t` looks for.

The potential for test bugs with this setup is pretty high, and it's also why the tests can't run in parallel. Fixing this is non-trivial, though. I may get some round tuits to get to it at some point, though.

**Comment by mcsnolte** [comment]
Looks like the "recv" test (number 7) is only passing because a previous test published a message to `nr_test_hole-$unique` which is being consumed.  The `alarm` is not actually firing, and the `recv` method is not aborted after the five second timeout.

We came across this because we noticed that when trying to switch from Net::RabbitMQ to Net::AMQP::RabbitMQ we could no longer handle a HUP signal to abort a blocking `recv` call.  The timeout feature added to `recv` probably introduced this change in behavior.  Any ideas on how we could alter the timeout feature to allow a HUP to be handled?

**Comment by markwellis** [comment]
I can't remember how or why, but I thought I knew a way to fix this. So while that doesn't help, it does mean there is a way.

I'm planning on carving out some time soon and working on the open issues on this, and I'll see what I can do then.

In the meantime, if anyone has any ideas, please let me know

**Comment by manchicken** [comment]
Mark, you and I should schedule time together. A virtual hackathon. It'll
be fun.

**Comment by markwellis** [comment]
sure! what's your timezone? I'm currently GMT+1, and it'll have to be a weekend, unless I can think up any awesome features work would need!

**Comment by manchicken** [comment]
I'm -0400 for now :-)

How is October 11th for you? Maybe that's enough time to get someone else
on board.

**Comment by markwellis** [comment]
Oct 11th sounds good to me!

**Comment by manchicken** [comment]
14:00 UTC?

**Comment by markwellis** [comment]
I can't do the 11th actually, can do the 12th though

**Comment by markwellis** [comment]
Change the test suite so the tests can be run in isolation/parallel, and also have proper unique identifiers so that they don't conflict with other people running the tests

**Comment by manchicken** [comment]
So, I just went through and made a pull request (#82) and merged it. This test suite change made the tests clean up after themselves. It's possible that I missed a spot or two. Please review if you like.

**Comment by markwellis** [comment]
i'm going to change the tests to the new rabbitmq server and other things, then move onto the ssl stuff #48
