### ISSUE TITLE
The recv() method should (maybe?) call amqp_consume_message

### ISSUE THREAD

**Issue by autarch** [net-amqp-rabbitmq/net-amqp-rabbitmq#33]
I was looking into adding the possibility of a timeout to the `recv()` call. Internally, the `recv()` method calls `internal_recv()` which then calls `amqp_simple_wait_frame()`.

However, librabbitmq provides a `amqp_consume_message` which returns a message for a consumer *and* accepts a timeout. It seems like Net::AMQP::RabbitMQ should be using that API. If the `amqp_consume_message` gets a non-message frame you can still call `amqp_simple_wait_frame()` to get the frame and figure out what it is.

I could work on this change if you agree that it's the right way to go. I think I'd get rid of internal_recv() entirely and move message handling to its own sub, to be shared by `recv()` and `get()`.

Alternatively, I could make `internal_recv()` accept a timeout parameter and call `amqp_simple_wait_frame_noblock()` with a timeout, if one is given. I'll probably try this for now, since it's a relatively simply change and I'm not 100% that even with a timeout I can get my queue workers acting the way I want, so I might as well test it the easy way.

**Comment by markwellis** [comment]
That makes sense. It's how it is now because that's how the other library did it, but they also had a call back method we don't, so we have the complexity without the benefit I guess. I'm not really sure!

But what you said sounds good to me, and I was never happy with the whole internal_recv thing, but I don't know enough about librabbitmq or c/XS to make it better!

**Comment by autarch** [comment]
Yeah, internal_recv() is pretty gross. If I have a chance, I'll try to fix this up more. For now I'm going to try the simplest solution to getting recv() to accept a timeout.

**Comment by ikegami** [comment]
This issue can be closed as completed.
