### ISSUE TITLE
Feature Request: Missing nack functionality

### ISSUE THREAD

**Issue by noshankus** [net-amqp-rabbitmq/net-amqp-rabbitmq#38]
Hi Guys,

hope this is the right place for adding features too :)

I noticed that RabbitMQ has a nice nack feature which allows you to either tell RabbitMQ to discard or requeue the messages **in bulk**:
https://www.rabbitmq.com/nack.html

Currently, nothing short of disconnecting from RabbitMQ (or rebuilding and re-publishing the messages) will requeue the non-acked messages. Also, nothing short of ack-ing the message and discarding it by the consumer will discard the messages.

Not a biggy, but would be nice :)

**Comment by abraxxa** [comment]
I'd love to see that feature as well so that Message::Passing could not ack the messages in case an output module failed.

**Comment by manchicken** [comment]
Sure, I'll do this.

**Comment by markwellis** [comment]
this is in version 1.3 which will be on cpan shortly
