### ISSUE TITLE
SSL/TLS connections?

### ISSUE THREAD

**Issue by doconeill** [net-amqp-rabbitmq/net-amqp-rabbitmq#48]
I may be missing something, but I don't seem to be finding any way to establish SSL/TLS-based connections, even though the underlying library supports it. I thought it might be an undocumented pass-through to the library, but I tried setting "ssl", "use_ssl" and "tls" in the connection hash to "1" (those are the various names used in other modules), but all I ever get is 

Logging in: failed since AMQP socket connection closed.

Looking at the code I don't see much that tells me how to establish the connection, although there does seem support for it. amqp_url.c makes reference to using an "amqps://" URL, but not sure how that is utilized...

I REALLY would like to go back to this simpler method instead of using Coro/Net::RabbitFoot, but SSL is a requirement.

**Comment by manchicken** [comment]
I'll look at this at some point in the next week, I don't know whether or
not I'll be able to give you a good answer by then though.

**Comment by doconeill** [comment]
Thanks for looking

**Comment by manchicken** [comment]
Color me surprised, @doconeill, currently SSL support (which appears to be implemented in the library) does not appear to be bound in the Perl module.

I'm kind of surprised by this, and we should probably resolve this. As soon as I get the time, I will work on this.

**Comment by doconeill** [comment]
just wondering if there has been any chance to look at this further...

**Comment by macdonaldj** [comment]
any word @manchicken when this will be resolved?

**Comment by markwellis** [comment]
We have scheduled a hackathon for Oct 11th iirc, I plan to get it done
then! Sorry for the delay, its a struggle to find time!

**Comment by manchicken** [comment]
We will get it done then!

**Comment by macdonaldj** [comment]
thanks for the response!

**Comment by doconeill** [comment]
Sweet! Thanks...I recently changed one of my scripts from Net::RabbitFoot to Net::AMQP::RabbitMQ since I don't _need_ it to be event driven, and CPU usage dropped by two thirds... :) I just need the SSL side for external use.

**Comment by markwellis** [comment]
hi @doconeill  i had a go at getting this done, but it turns out to be more work than i thought. The big problem i'm having is setting up rabbitmq to allow ssl connections, and lack of time to investigate why it's not working.

is there any chance you can send me your rabbitmq.config so i can get a test server setup and get the tests working.

cheers

**Comment by doconeill** [comment]
Sure...the config is pretty basic. I set it up to listen on port 5673, and provided the SSL key, cert, and a CA cert that may not even be necessary:

[
  {rabbit, [
     {ssl_listeners, [5673]},
     {ssl_options, [{cacertfile,"/etc/rabbitmq/cacert.pem"},
                    {certfile,"/etc/rabbitmq/cert.pem"},
                    {keyfile,"/etc/rabbitmq/key.pem"},
                    {verify,verify_peer},
                    {fail_if_no_peer_cert,false}]}
   ]}
].

**Comment by markwellis** [comment]
thanks @doconeill I've got this working now, but I have to improve the test situation first in order to make sure it works.

So I'll do #53 first, and then enough of #27 that I'm sure it's working, hopefully that will all be done soon and it should be released before the week is up :)

**Comment by markwellis** [comment]
this has been released to cpan as version 1.4

**Comment by doconeill** [comment]
Excellent...thanks. I'll grab it and start testing as soon as I can!
