### ISSUE TITLE
Feature Request: Exchange Binding

### ISSUE THREAD

**Issue by alnewkirk** [net-amqp-rabbitmq/net-amqp-rabbitmq#52]
Since RabbitMQ 2.1.1, there is support for bindings between exchanges, i.e. exchange-to-exchange binding. From what I understand, it is semantically the same as the queue binding functionality and implementation.

**Comment by manchicken** [comment]
I found this defined in our `librabbitmq-c` dependency, and it was rather simple. I've implemented this in pull request #81, and we'll see if it passes tests.

It seems like this may be a RabbitMQ extension, and as such could have version compatibility issues. We will see how the test matrix feels about this change, and if it becomes a bother then we can figure out how to mitigate this (if necessary).

**Comment by manchicken** [comment]
Ack, this wasn't meant to be closed yet.

**Comment by markwellis** [comment]
this is in version 1.200000 which will be on cpan shortly

**Comment by alnewkirk** [comment]
@markwellis @manchicken Thanks very much. This is great news. For advanced topologies, I've been resorting to installing a python tool and doing an JSON import of the configuration. Now I can do it all in code. :+1:
