### ISSUE TITLE
Consumer cancel event?

### ISSUE THREAD

**Issue by GeoffTK** [net-amqp-rabbitmq/net-amqp-rabbitmq#62]
I have just come across a situation that I need to handle in my code given that I am on RabbitMQ 3.1 and not 3.3+. Before rabbit version 3.3, if you consume from a mirrored queue and your channel is open on one of the slaves, when the master node goes down the consumer is cancelled. This occurs because the consumer is always placed on the master node. The connection/channel itself is still open because it is on a still live slave (that may have now become the master).

My question is this: Is there anyway to be notified of that consumer's cancel event using this module, or can you think of any other simple way to handle this situation. Sadly, upgrading rabbit to version 3.3 is not an option, so I need to somehow find a work around.
Thanks in advance for any info you may be able to provide!

**Comment by markwellis** [comment]
sorry @GeoffTK, I don't know how to do what you want :(

@manchicken do you have any ideas?

**Comment by GeoffTK** [comment]
I was able to convince the powers that be to upgrade to rabbit 3.5, so this is no longer an issue for me. However, it might be nice to keep open as I am still interested in how one might detect these events from the channel.

**Comment by manchicken** [comment]
Yeah, random disconnects are things you will have to deal with sometimes.

**Comment by manchicken** [comment]
The stupid send button was next to my mobile keyboard. The cancel event is part of the protocol, no? @markwellis, do you see any tests in librabbitmq-c that would handle this? I could also be thinking of the client side cancel send RPC call, it's been a while since I dug into the library.

**Comment by markwellis** [comment]
sorry i have no idea. i'm going to close the issue since no one knows and you fixed it by upgrading. hope that's ok
