### ISSUE TITLE
Tests fail with -Duselongdouble

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#68]
Again sample test report http://www.cpantesters.org/cpan/report/11907dc8-676a-11e5-848a-573096b0373b : t/023_numeric_header_fields.t fails, probably because caused by a perl built with long double support.

**Comment by markwellis** [comment]
is this the same as #11?

**Comment by eserte** [comment]
Yes. But with a slightly better issue title ;-)

**Comment by markwellis** [comment]
I'm closing this as a duplicate of #11, but stealing the better title for it :)
