### ISSUE TITLE
Trouble with field types during communication with Spring AMQP on the other end

### ISSUE THREAD

**Issue by DavsX** [net-amqp-rabbitmq/net-amqp-rabbitmq#69]
Hi!
My problem is, that if I send a string (non UTF-8 SvPV type), then the type AMQP_FIELD_KIND_BYTES (x) is set, which is then in Spring AMQP interpreted as an array, resulting in "nonsense" like "[B@123143" instead of the string itself.

AMQP_FIELD_KIND_BYTES is not part of the AMQP specification: see the comments in librabbitmq-c [here](https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp.h#L441)

The problem I get is when I send some `headers` inside `props`. What would happen, if we were to set force_utf8 to 1 [here](https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/blob/master/RabbitMQ.xs#L1315) . Is sending non-utf8 strings as utf8 a problem?

One other solution for me would be to Encode::encode_utf8 or utf8::upgrade_utf8 my ASCII strings inside my Perl code, which seems non-ideal and also has some performance cost. Do you have any suggestion as how to handle this issue?

**Comment by markwellis** [comment]
i have no idea, i've never heard of Spring AMQP before. but i do know sending non-utf8 strings as utf8 is a problem, unless it happens to be ascii, in which case some of it lines up (on purpose). but for everything else it can only cause problems

**Comment by manchicken** [comment]
I would be okay adding a property to force all things to UTF8. I know in
the past the opposite has been true for me - which is why we stopped
assuming all strings were UTF8 in the first place.

@markwellis, I like Dávid's suggested implementation. What are your
thoughts?

**Comment by DavsX** [comment]
To be clear: I'm suggesting to force UTF-8 only on props->{headers}. (Maybe it is fine to force it everywhere - not sure)

**Comment by manchicken** [comment]
Yeah, I've got that. It's simple, downgrades well, and is easy to document.

**Comment by DavsX** [comment]
Interesting comment on the subject; they suggest, that header values should be ASCII or UTF-8, but apparently the specification is not clear on the subject: https://github.com/gmr/rabbitpy/issues/51#issuecomment-62707652

**Comment by markwellis** [comment]
ah, i misunderstood. yeah sounds like a plan, lets go for it!

**Comment by DavsX** [comment]
https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/pull/71

**Comment by manchicken** [comment]
@DavsX: Please look at #78.

**Comment by markwellis** [comment]
this is released in version 1.1, which will be on cpan shortly
