### ISSUE TITLE
tidy docs, add examples

### ISSUE THREAD

**Issue by markwellis** [net-amqp-rabbitmq/net-amqp-rabbitmq#70]
see https://rt.cpan.org/Public/Bug/Display.html?id=71337 for example examples

**Comment by markwellis** [comment]
add docs for `nack` as well

**Comment by giganteous** [comment]
Can I help with adding examples? Do you have any plans laid out somewhere? Or can I change RabbitMQ.pm and sprinke examples for consuming a queue and filling an exchange?

**Comment by CTrabant** [comment]
Hopefully helpful, I created a PR #123 with my edits to the documentation.

**Comment by markwellis** [comment]
thanks @CTrabant
