### ISSUE TITLE
Publisher confirms

### ISSUE THREAD

**Issue by DavsX** [net-amqp-rabbitmq/net-amqp-rabbitmq#72]
Hi!
Is there a way to use/receive [publisher confirms](https://www.rabbitmq.com/confirms.html)? Based on the docs/code i've seen this is currently unsupported. Any plans for enabling this?

When you turn it on and publish a message to an exchange, the RabbitMQ should send back an ACK about successfully receiving that message.

**Comment by markwellis** [comment]
if the underlying library (librabbitmq-c) supports it i'm sure we can add
it to the list of things that we might get round to adding one day. if it
doesn't, then no.

a quick look leaves me thinking it doesn't :(

**Comment by DavsX** [comment]
I'm thinking it should have something to do with this: https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp_framing.c#L2393

**Comment by markwellis** [comment]
ok, seems it can be done.

here's what alanxz has to say on it,
http://rabbitmq.1065348.n5.nabble.com/rabbitmq-c-confirmation-td27910.html

and here's an example,
http://rabbitmq.1065348.n5.nabble.com/Publisher-Confirms-support-in-Rabbitmq-c-client-td20862.html#a20867

**Comment by manchicken** [comment]
What would the Perl example look like, this?

```perl
$mq->confirm_select(1, sub {
   say "Successful ack!";
});

$mq->publish(...);
```

Something like that is the only thing which comes to mind as a usable convention in modern Perl. Thoughts?

**Comment by manchicken** [comment]
Maybe:

```perl
$mq->confirm_select_init(1);
$mq->publish(1, ...);
$response = $mq->confirm_select_wait(1, $seconds_to_wait);
say "I got a $response->{method} response, with a body of $response->{body}";
```

I suppose I could see that as well, where we return the response method and body.

**Comment by markwellis** [comment]
i like the second

**Comment by DavsX** [comment]
The second looks fine for me too

**Comment by dz-at-tc** [comment]
Hi all!  Would it be possible to Hacktoberfest tag this issue?  Alas, I don't know C, but I think publisher confirms in Perl would be quite useful for some workflows (including mine! :).  No worries if not, just figured it couldn't hurt to ask, thanks!

**Comment by manchicken** [comment]
> Hi all! Would it be possible to Hacktoberfest tag this issue? Alas, I don't know C, but I think publisher confirms in Perl would be quite useful for some workflows (including mine! :). No worries if not, just figured it couldn't hurt to ask, thanks!

Done

**Comment by dz-at-tc** [comment]
Hi @manchicken ,  thanks mate!  Fingers crossed that someone is feelin feisty in Q4...  :)

**Comment by dz-at-tc** [comment]
hey there @manchicken, nice to see you again, thanks for merging #198 and #200!

i'm curious if you or anyone else has any bandwidth to move this publisher confirms issue forward anytime soon?

we've had some cases where sometimes publishing just silently fails from time to time, so confirms would surely help out here (right, but stop calling me shirley!  womp womp :).

**Comment by manchicken** [comment]
I’m trying to figure out the best path forward on that with the maintainer of the C lib. 

I’m not sure how to implement such a thing. 

~ Michael D. Stemle, Jr.

**Comment by abraxxa** [comment]
I've added the following code to deal with publish failures due to missing write access to the exchange:

```
# publish never returns anything and also doesn't throw an exception on
# for example access errors
# wait 500ms
my $rv = $self->_client->recv(500);
die $rv
    if defined $rv;
```

That's quite similar to the suggestion @manchicken provided.

**Comment by manchicken** [comment]
Publisher confirms are being planned for later, but there's a lot of cleanup needed still. This issue is still deferred.

**Comment by manchicken** [comment]
Update for y'all: I have a PR for `rabbitmq-c` which adds some support for waiting for publisher confirms: https://github.com/alanxz/rabbitmq-c/pull/841

One way or another, publisher confirms are _coming soon_.

**Comment by manchicken** [comment]
Ok, that PR was merged, so I'm now starting work on this.
