### ISSUE TITLE
test fails on freebsd/netbsd

### ISSUE THREAD

**Issue by markwellis** [net-amqp-rabbitmq/net-amqp-rabbitmq#74]
they all fail like this

Failed test 'Timeout about 1.2 second'
 at t/003_consume.t line 70.
Looks like you failed 1 test of 18.
t/003_consume.t ..................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/18 subtests 

Net-AMQP-RabbitMQ-1.001000:
- amd64-netbsd / 5.12.4:
  - FAIL http://www.cpantesters.org/cpan/report/90f56fa2-6d63-11e5-9563-166b02dd8615

- amd64-netbsd / 5.12.5:
  - FAIL http://www.cpantesters.org/cpan/report/6b7eca64-6da6-11e5-9563-166b02dd8615

- amd64-netbsd / 5.14.0:
  - FAIL http://www.cpantesters.org/cpan/report/0bc46d30-6ded-11e5-9563-166b02dd8615

- amd64-netbsd-thread-multi / 5.12.4:
  - FAIL http://www.cpantesters.org/cpan/report/121c6272-6d85-11e5-9563-166b02dd8615

- amd64-netbsd-thread-multi / 5.12.5:
  - FAIL http://www.cpantesters.org/cpan/report/2a5c7d96-6dca-11e5-9563-166b02dd8615

- x86_64-gnukfreebsd / 5.16.3:
  - FAIL http://www.cpantesters.org/cpan/report/b6ebb1ec-6dbf-11e5-aa10-096acfe82091

- x86_64-gnukfreebsd / 5.18.0:
  - FAIL http://www.cpantesters.org/cpan/report/6e5084e4-6d92-11e5-aa10-096acfe82091

- x86_64-gnukfreebsd / 5.18.1:
  - FAIL http://www.cpantesters.org/cpan/report/c96f8ff0-6d65-11e5-aa10-096acfe82091

- x86_64-gnukfreebsd-thread-multi / 5.16.3:
  - FAIL http://www.cpantesters.org/cpan/report/96d5acec-6dd7-11e5-aa10-096acfe82091

- x86_64-gnukfreebsd-thread-multi / 5.18.0:
  - FAIL http://www.cpantesters.org/cpan/report/fb90b92c-6da7-11e5-aa10-096acfe82091

- x86_64-gnukfreebsd-thread-multi / 5.18.1:
  - FAIL http://www.cpantesters.org/cpan/report/87e310c8-6d7b-11e5-aa10-096acfe82091

**Comment by manchicken** [comment]
I want to see if I can figure out how to get Travis to test FreeBSD as
well.

**Comment by markwellis** [comment]
I don't think it can :(

**Comment by manchicken** [comment]
Nope, it cannot: https://github.com/travis-ci/travis-ci/issues/1818

I'm at a loss for how to test this. I'll dig into the CPAN stuff. Maybe there's a CPAN tester who could help out.

**Comment by markwellis** [comment]
I've got a freebsd VM to check it on, but I've not got round to it yet!
