### ISSUE TITLE
stop using bits of librabbitmq-c private api

### ISSUE THREAD

**Issue by ppisar** [net-amqp-rabbitmq/net-amqp-rabbitmq#93]
The Net-AMQP-RabbitMQ-1.400000 bundles rabbitmq sources and uses rabbitmq's private functions. This is very bad practise as it does not allow to build it against system  version of the rabbitmq library, thus hindering any maintainability and security of such system. In other words it duplicates code.

I found these misuses of private API:

Calls to amqp_socket_close(). Ask rabbitmq upstream to make it public. Or replace it with stronger amqp_destroy_connection() calls.

Calls to amqp_get_or_create_channel_pool(). I have no idea why net_amqp_rabbitmq_tx_commit() needs to call it.

Dereferencing  amqp_connection_state_t variable to access "state" member. This can be fixed by calling amqp_get_socket().

It would be great to change the Perl's implementation or to cooperate with rabbitmq author to make the rabbitmq compatible with Net-AMQP-RabbitMQ and to make Net-AMQP-RabbitMQ not depending on rabbitmq internals. I believe authors of other bindings to the rabbitmq library would benefit from it either.

**Comment by markwellis** [comment]
this is because the system versions of librabbitmq are too old.

as for the problems you listed, i can look into them. it would be easier if you could like to errors in the source?

**Comment by markwellis** [comment]
the amqp_get_or_create_channel_pool call in net_amqp_rabbitmq_tx_commit is left over code that i should have deleted but didn't.

**Comment by markwellis** [comment]
as for amqp_destroy_connection, yeah that makes sense. pr's welcome :)

**Comment by ppisar** [comment]
I'm not expert on the rabbitmq. Here <https://github.com/ppisar/net-amqp-rabbitmq/commit/e782050cec7c18009e511cd93a424491dc1eb0e0> is a naive patch that avoids using non-public API and links against system rabbitmq (located by pkgconfig). You can use it see the problematic places in the code.

All tests pass except t/018_is_connected.t on line 14. That's because the amqp_connection_close() disconnects only on the messaging level, but keeps the socket opened.

The patch is not meant to be ready for inclusion to your code. It would need more thorough changes for what I have no rabbitmq knowledge. The Makefile.PL part of course could be made better to fall back to the bundled code if system does not provide new enough rabbitmq. Also the pkgconfig usage could be made more robust all avoided and implemented differently.

**Comment by markwellis** [comment]
@ppisar looks good, i can do something with this, i'll come up with a plan and try and make some time to get it done

**Comment by markwellis** [comment]
I'm not going to get time to do this, and tbh it's not a priority, so I'm going to close it wontfix.

**Comment by markwellis** [comment]
infact there's some bugs here, so i'm reopening. but changing the title

**Comment by markwellis** [comment]
Fixed in version 2.30000, which will be on cpan shortly
