### ISSUE TITLE
SSL tests don't support MQHOST

### ISSUE THREAD

**Issue by fgabolde** [net-amqp-rabbitmq/net-amqp-rabbitmq#94]
The SSL tests at `t/030_ssl.t` create an instance of NAR::Helper hardcoded to use the remote RabbitMQ server:

```perl
my $helper = NAR::Helper->new(
    ssl        => 1,
    port       => 5673,
    host       => 'rabbitmq.thisaintnews.com',
    ssl_cacert => "$Bin/ssl/cacert.pem",
    ssl_init   => 1,
    username   => 'nartest',
    password   => 'reallysecure',
);
```

This is unfortunate as all the other tests respect the `MQHOST` variable.  Was this an oversight?  If so, I can provide a patch.

**Comment by markwellis** [comment]
Its because SSL isn't enabled by default, and he port isn't standard. So
there's a good chance that SSL isn't available on the user provided MQHOST,
hence the hardcoding

**Comment by fgabolde** [comment]
> Its because SSL isn't enabled by default, and he port isn't
> standard. So there's a good chance that SSL isn't available on the
> user provided MQHOST, hence the hardcoding

I was thinking of checking `MQSSL` to see if the SSL tests should be
enabled, but sadly it defaults to 0.  That would mean the SSL tests
would be disabled by default, which I assume we don't want either.

I worked around this with a new `MQSKIPSSL` variable that controls
only whether the SSL tests should be skipped.  If it is not set, the
tests will also attempt to respect MQHOST and others, but use the
current SSL configuration if not provided.  It's rather awkward, but
currently I can't even ping the test server, so...

See the commit here: fgabolde@2215e7fe6ac798a02fdedebb89145cfc09a10969

Does this work for you?

**Comment by markwellis** [comment]
Looks good to me, can you send a PR? Thanks

**Comment by fgabolde** [comment]
Here you go: #110

**Comment by markwellis** [comment]
thanks :+1:
