### ISSUE TITLE
Default of auto_delete for declare_exchange misdocumented

### ISSUE THREAD

**Issue by ikegami** [net-amqp-rabbitmq/net-amqp-rabbitmq#98]
There's a discrepancy between the docs and the implementation about the default value of auto_delete for declare_exchange.

Docs for exchange_declare:

    {
        exchange_type => $type,  #default 'direct'
        passive => $boolean,     #default 0
        durable => $boolean,     #default 0
        auto_delete => $boolean, #default 1
    }

Definition of exchange_declare:

    PREINIT:
        char *exchange_type = "direct";
        int passive = 0;
        int durable = 0;
        int auto_delete = 0;
        int internal = 0;
        amqp_table_t arguments = amqp_empty_table;

**Comment by ikegami** [comment]
Should the code by changed to match the docs, or should the docs be changed to match the code? I presume the latter (for backwards-compatibility) even though I prefer the documented default.

**Comment by markwellis** [comment]
I say docs changed to match the code, for the reasons @ikegami says above. It's a shame, the documented default is nicer, but this way there's no way we're breaking things when people upgrade
